all:
	cd codegenasm && $(MAKE) TARGET=$(TARGET) all
	cd dumpicode && $(MAKE) TARGET=$(TARGET) all
	cd dumpsymtab && $(MAKE) TARGET=$(TARGET) all
	cd editorasm && $(MAKE) TARGET=$(TARGET) all
	cd icodeasm && $(MAKE) TARGET=$(TARGET) all
	cd linkerasm && $(MAKE) TARGET=$(TARGET) all
	cd parserasm && $(MAKE) TARGET=$(TARGET) all
	cd resolverasm && $(MAKE) TARGET=$(TARGET) all
	cd tokenizerasm && $(MAKE) TARGET=$(TARGET) all
	cd typecheckasm && $(MAKE) TARGET=$(TARGET) all

clean:
	cd codegenasm && $(MAKE) TARGET=$(TARGET) clean
	cd dumpicode && $(MAKE) TARGET=$(TARGET) clean
	cd dumpsymtab && $(MAKE) TARGET=$(TARGET) clean
	cd editorasm && $(MAKE) TARGET=$(TARGET) clean
	cd icodeasm && $(MAKE) TARGET=$(TARGET) clean
	cd linkerasm && $(MAKE) TARGET=$(TARGET) clean
	cd parserasm && $(MAKE) TARGET=$(TARGET) clean
	cd resolverasm && $(MAKE) TARGET=$(TARGET) clean
	cd tokenizerasm && $(MAKE) TARGET=$(TARGET) clean
	cd typecheckasm && $(MAKE) TARGET=$(TARGET) clean
