;;;
 ; types.inc
 ; Ken Schenke (kenschenke@gmail.com)
 ; 
 ; Data type constants
 ; 
 ; Copyright (c) 2024
 ; Use of this source code is governed by an MIT-style
 ; license that can be found in the LICENSE file or at
 ; https://opensource.org/licenses/MIT
;;;

; Data Types

TYPE_BYTE = 1
TYPE_SHORTINT = 2
TYPE_WORD = 3
TYPE_INTEGER = 4
TYPE_CARDINAL = 5
TYPE_LONGINT = 6
TYPE_REAL = 7
TYPE_BOOLEAN = 8
TYPE_CHARACTER = 9
TYPE_STRING_LITERAL = 10
TYPE_ARRAY = 11
TYPE_ENUMERATION = 18
TYPE_STRING_VAR = 21
TYPE_STRING_OBJ = 22
TYPE_POINTER = 27
TYPE_ADDRESS = 28
TYPE_ROUTINE_ADDRESS = 29
TYPE_ROUTINE_POINTER = 30
