all:
	cd compiler && $(MAKE) TARGET=$(TARGET) all
	cd ide && $(MAKE) TARGET=$(TARGET) all
	cd lib && $(MAKE) TARGET=$(TARGET) all

clean:
	cd compiler && $(MAKE) TARGET=$(TARGET) clean
	cd ide && $(MAKE) TARGET=$(TARGET) clean
	cd lib && $(MAKE) TARGET=$(TARGET) clean
