(* Test 2 - Expressions
D:DECL-TYPE test
  T:TYPE-PROGRAM
  S:STMT-BLOCK
    D:DECL-USES system
      T:TYPE-UNIT
    D:DECL-VARIABLE a
      T:TYPE-SHORTINT
    D:DECL-VARIABLE b
      T:TYPE-BYTE
    D:DECL-VARIABLE bool
      T:TYPE-BOOLEAN
    D:DECL-VARIABLE i
      T:TYPE-INTEGER
    D:DECL-VARIABLE j
      T:TYPE-INTEGER
    D:DECL-VARIABLE r
      T:TYPE-REAL
    D:DECL-VARIABLE str
      T:TYPE-STRING-VAR
    S:STMT-EXPR
      E:EXPR-ASSIGN T:TYPE-SHORTINT
        Left:EXPR-NAME a T:TYPE-SHORTINT
        Right:EXPR-ADD T:TYPE-CARDINAL
          Left:EXPR-NAME b T:TYPE-BYTE
          Right:EXPR-BYTE-LITERAL 1 T:TYPE-SHORTINT
    S:STMT-EXPR
      E:EXPR-ASSIGN T:TYPE-SHORTINT
        Left:EXPR-NAME a T:TYPE-SHORTINT
        Right:EXPR-MUL T:TYPE-CARDINAL
          Left:EXPR-NAME b T:TYPE-BYTE
          Right:EXPR-BYTE-LITERAL 3 T:TYPE-SHORTINT
    S:STMT-EXPR
      E:EXPR-ASSIGN T:TYPE-SHORTINT
        Left:EXPR-NAME a T:TYPE-SHORTINT
        Right:EXPR-SUB T:TYPE-CARDINAL
          Left:EXPR-NAME b T:TYPE-BYTE
          Right:EXPR-BYTE-LITERAL 5 T:TYPE-SHORTINT
    S:STMT-EXPR
      E:EXPR-ASSIGN T:TYPE-REAL
        Left:EXPR-NAME r T:TYPE-REAL
        Right:EXPR-DIV T:TYPE-REAL
          Left:EXPR-NAME b T:TYPE-BYTE
          Right:EXPR-BYTE-LITERAL 4 T:TYPE-SHORTINT
    S:STMT-EXPR
      E:EXPR-ASSIGN T:TYPE-SHORTINT
        Left:EXPR-NAME a T:TYPE-SHORTINT
        Right:EXPR-DIVINT T:TYPE-CARDINAL
          Left:EXPR-NAME b T:TYPE-BYTE
          Right:EXPR-BYTE-LITERAL 6 T:TYPE-SHORTINT
    S:STMT-EXPR
      E:EXPR-ASSIGN T:TYPE-SHORTINT
        Left:EXPR-NAME a T:TYPE-SHORTINT
        Right:EXPR-MOD T:TYPE-CARDINAL
          Left:EXPR-NAME b T:TYPE-BYTE
          Right:EXPR-BYTE-LITERAL 2 T:TYPE-SHORTINT
    S:STMT-EXPR
      E:EXPR-ASSIGN T:TYPE-BOOLEAN
        Left:EXPR-NAME bool T:TYPE-BOOLEAN
        Right:EXPR-LT T:TYPE-BOOLEAN
          Left:EXPR-NAME b T:TYPE-BYTE
          Right:EXPR-BYTE-LITERAL 2 T:TYPE-SHORTINT
    S:STMT-EXPR
      E:EXPR-ASSIGN T:TYPE-BOOLEAN
        Left:EXPR-NAME bool T:TYPE-BOOLEAN
        Right:EXPR-LTE T:TYPE-BOOLEAN
          Left:EXPR-NAME b T:TYPE-BYTE
          Right:EXPR-BYTE-LITERAL 8 T:TYPE-SHORTINT
    S:STMT-EXPR
      E:EXPR-ASSIGN T:TYPE-BOOLEAN
        Left:EXPR-NAME bool T:TYPE-BOOLEAN
        Right:EXPR-GT T:TYPE-BOOLEAN
          Left:EXPR-NAME b T:TYPE-BYTE
          Right:EXPR-BYTE-LITERAL 7 T:TYPE-SHORTINT
    S:STMT-EXPR
      E:EXPR-ASSIGN T:TYPE-BOOLEAN
        Left:EXPR-NAME bool T:TYPE-BOOLEAN
        Right:EXPR-GTE T:TYPE-BOOLEAN
          Left:EXPR-NAME b T:TYPE-BYTE
          Right:EXPR-BYTE-LITERAL 9 T:TYPE-SHORTINT
    S:STMT-EXPR
      E:EXPR-ASSIGN T:TYPE-BOOLEAN
        Left:EXPR-NAME bool T:TYPE-BOOLEAN
        Right:EXPR-NE T:TYPE-BOOLEAN
          Left:EXPR-NAME b T:TYPE-BYTE
          Right:EXPR-BYTE-LITERAL 1 T:TYPE-SHORTINT
    S:STMT-EXPR
      E:EXPR-ASSIGN T:TYPE-BOOLEAN
        Left:EXPR-NAME bool T:TYPE-BOOLEAN
        Right:EXPR-AND T:TYPE-BOOLEAN
          Left:EXPR-LT T:TYPE-BOOLEAN
            Left:EXPR-NAME b T:TYPE-BYTE
            Right:EXPR-BYTE-LITERAL 2 T:TYPE-SHORTINT
          Right:EXPR-GTE T:TYPE-BOOLEAN
            Left:EXPR-NAME i T:TYPE-INTEGER
            Right:EXPR-BYTE-LITERAL 5 T:TYPE-SHORTINT
    S:STMT-EXPR
      E:EXPR-ASSIGN T:TYPE-BOOLEAN
        Left:EXPR-NAME bool T:TYPE-BOOLEAN
        Right:EXPR-OR T:TYPE-BOOLEAN
          Left:EXPR-GT T:TYPE-BOOLEAN
            Left:EXPR-NAME b T:TYPE-BYTE
            Right:EXPR-BYTE-LITERAL 5 T:TYPE-SHORTINT
          Right:EXPR-NE T:TYPE-BOOLEAN
            Left:EXPR-NAME i T:TYPE-INTEGER
            Right:EXPR-BYTE-LITERAL 6 T:TYPE-SHORTINT
    S:STMT-EXPR
      E:EXPR-ASSIGN T:TYPE-BOOLEAN
        Left:EXPR-NAME bool T:TYPE-BOOLEAN
        Right:EXPR-NOT T:TYPE-BOOLEAN
          Left:EXPR-GT T:TYPE-BOOLEAN
            Left:EXPR-NAME b T:TYPE-BYTE
            Right:EXPR-BYTE-LITERAL 6 T:TYPE-SHORTINT
    S:STMT-EXPR
      E:EXPR-ASSIGN T:TYPE-INTEGER
        Left:EXPR-NAME i T:TYPE-INTEGER
        Right:EXPR-BITWISE-AND T:TYPE-INTEGER
          Left:EXPR-NAME a T:TYPE-SHORTINT
          Right:EXPR-NAME j T:TYPE-INTEGER
    S:STMT-EXPR
      E:EXPR-ASSIGN T:TYPE-INTEGER
        Left:EXPR-NAME i T:TYPE-INTEGER
        Right:EXPR-BITWISE-OR T:TYPE-INTEGER
          Left:EXPR-NAME a T:TYPE-SHORTINT
          Right:EXPR-NAME j T:TYPE-INTEGER
    S:STMT-EXPR
      E:EXPR-ASSIGN T:TYPE-INTEGER
        Left:EXPR-NAME i T:TYPE-INTEGER
        Right:EXPR-BITWISE-LSHIFT T:TYPE-INTEGER
          Left:EXPR-NAME j T:TYPE-INTEGER
          Right:EXPR-BYTE-LITERAL 4 T:TYPE-SHORTINT
    S:STMT-EXPR
      E:EXPR-ASSIGN T:TYPE-INTEGER
        Left:EXPR-NAME i T:TYPE-INTEGER
        Right:EXPR-BITWISE-RSHIFT T:TYPE-INTEGER
          Left:EXPR-NAME j T:TYPE-INTEGER
          Right:EXPR-BYTE-LITERAL 5 T:TYPE-SHORTINT
    S:STMT-EXPR
      E:EXPR-ASSIGN T:TYPE-INTEGER
        Left:EXPR-NAME i T:TYPE-INTEGER
        Right:EXPR-NOT T:TYPE-INTEGER
          Left:EXPR-NAME j T:TYPE-INTEGER
    S:STMT-EXPR
      E:EXPR-ASSIGN T:TYPE-INTEGER
        Left:EXPR-NAME i T:TYPE-INTEGER
        Right:EXPR-BITWISE-XOR T:TYPE-INTEGER
          Left:EXPR-NAME a T:TYPE-SHORTINT
          Right:EXPR-NAME i T:TYPE-INTEGER
    S:STMT-EXPR
      E:EXPR-ASSIGN T:TYPE-INTEGER
        Left:EXPR-NAME i T:TYPE-INTEGER
        Right:EXPR-ADD T:TYPE-LONGINT
          Left:EXPR-NAME b T:TYPE-BYTE
          Right:EXPR-MUL T:TYPE-LONGINT
            Left:EXPR-NAME j T:TYPE-INTEGER
            Right:EXPR-BYTE-LITERAL 5 T:TYPE-SHORTINT
    S:STMT-EXPR
      E:EXPR-ASSIGN T:TYPE-INTEGER
        Left:EXPR-NAME i T:TYPE-INTEGER
        Right:EXPR-MUL T:TYPE-LONGINT
          Left:EXPR-ADD T:TYPE-LONGINT
            Left:EXPR-NAME b T:TYPE-BYTE
            Right:EXPR-NAME j T:TYPE-INTEGER
          Right:EXPR-BYTE-LITERAL 5 T:TYPE-SHORTINT
    S:STMT-EXPR
      E:EXPR-ASSIGN T:TYPE-REAL
        Left:EXPR-NAME r T:TYPE-REAL
        Right:EXPR-ADD T:TYPE-REAL
          Left:EXPR-NAME r T:TYPE-REAL
          Right:EXPR-REAL-LITERAL 3.14 T:TYPE-REAL
    S:STMT-EXPR
      E:EXPR-ASSIGN T:TYPE-STRING-OBJ
        Left:EXPR-NAME str T:TYPE-STRING-VAR
        Right:EXPR-ADD T:TYPE-STRING-OBJ
          Left:EXPR-NAME str T:TYPE-STRING-VAR
          Right:EXPR-STRING-LITERAL World T:TYPE-STRING-LITERAL
*)

Program Test;

Var
  a : ShortInt;
  b : Byte;
  bool : Boolean;
  i, j : Integer;
  r : Real;
  str : String;

Begin
  a := b + 1;
  a := b * 3;
  a := b - 5;
  r := b / 4;
  a := b Div 6;
  a := b Mod 2;
  bool := b < 2;
  bool := b <= 8;
  bool := b > 7;
  bool := b >= 9;
  bool := b <> 1;
  bool := (b < 2) And (i >= 5);
  bool := (b > 5) Or (i <> 6);
  bool := Not (b > 6);
  i := a & j;
  i := a ! j;
  i := j << 4;
  i := j >> 5;
  i := Not j;
  i := a Xor i;
  i := b + j * 5;
  i := (b + j) * 5;
  r := r + 3.14;
  str := str + 'World';
End.
