(* Test 6 - Arrays
D:DECL-TYPE test
  T:TYPE-PROGRAM
  S:STMT-BLOCK
    D:DECL-USES system
      T:TYPE-UNIT
    D:DECL-VARIABLE arr1
      T:TYPE-ARRAY  1.. 5 OF TYPE-INTEGER
    D:DECL-VARIABLE arr2
      T:TYPE-ARRAY  0.. 4 OF TYPE-ARRAY  0.. 4 OF TYPE-INTEGER
    D:DECL-VARIABLE i
      T:TYPE-INTEGER
    D:DECL-VARIABLE j
      T:TYPE-INTEGER
    S:STMT-EXPR
      E:EXPR-ASSIGN T:TYPE-INTEGER
        Left:EXPR-SUBSCRIPT T:TYPE-INTEGER
          Left:EXPR-NAME arr1 T:TYPE-ARRAY
          Right:EXPR-BYTE-LITERAL 3 T:TYPE-SHORTINT
        Right:EXPR-BYTE-LITERAL 5 T:TYPE-SHORTINT
    S:STMT-EXPR
      E:EXPR-ASSIGN T:TYPE-INTEGER
        Left:EXPR-SUBSCRIPT T:TYPE-INTEGER
          Left:EXPR-NAME arr1 T:TYPE-ARRAY
          Right:EXPR-ADD T:TYPE-LONGINT
            Left:EXPR-NAME i T:TYPE-INTEGER
            Right:EXPR-BYTE-LITERAL 1 T:TYPE-SHORTINT
        Right:EXPR-BYTE-LITERAL 6 T:TYPE-SHORTINT
    S:STMT-EXPR
      E:EXPR-ASSIGN T:TYPE-INTEGER
        Left:EXPR-SUBSCRIPT T:TYPE-INTEGER
          Left:EXPR-SUBSCRIPT T:TYPE-ARRAY
            Left:EXPR-NAME arr2 T:TYPE-ARRAY
            Right:EXPR-BYTE-LITERAL 3 T:TYPE-SHORTINT
          Right:EXPR-BYTE-LITERAL 5 T:TYPE-SHORTINT
        Right:EXPR-BYTE-LITERAL 2 T:TYPE-SHORTINT
    S:STMT-EXPR
      E:EXPR-ASSIGN T:TYPE-INTEGER
        Left:EXPR-SUBSCRIPT T:TYPE-INTEGER
          Left:EXPR-SUBSCRIPT T:TYPE-ARRAY
            Left:EXPR-NAME arr2 T:TYPE-ARRAY
            Right:EXPR-ADD T:TYPE-LONGINT
              Left:EXPR-NAME i T:TYPE-INTEGER
              Right:EXPR-BYTE-LITERAL 1 T:TYPE-SHORTINT
          Right:EXPR-MUL T:TYPE-LONGINT
            Left:EXPR-NAME i T:TYPE-INTEGER
            Right:EXPR-BYTE-LITERAL 3 T:TYPE-SHORTINT
        Right:EXPR-BYTE-LITERAL 7 T:TYPE-SHORTINT
    S:STMT-EXPR
      E:EXPR-ASSIGN T:TYPE-INTEGER
        Left:EXPR-SUBSCRIPT T:TYPE-INTEGER
          Left:EXPR-SUBSCRIPT T:TYPE-ARRAY
            Left:EXPR-NAME arr2 T:TYPE-ARRAY
            Right:EXPR-NAME i T:TYPE-INTEGER
          Right:EXPR-ADD T:TYPE-LONGINT
            Left:EXPR-NAME j T:TYPE-INTEGER
            Right:EXPR-BYTE-LITERAL 1 T:TYPE-SHORTINT
        Right:EXPR-BYTE-LITERAL 8 T:TYPE-SHORTINT
*)

Program Test;

Var
  arr1 : Array[1..5] Of Integer;
  arr2 : Array[5,5] Of Integer;
  i, j : Integer;

Begin
  arr1[3] := 5;
  arr1[i+1] := 6;
  arr2[3,5] := 2;
  arr2[i+1,i*3] := 7;
  arr2[i][j+1] := 8;
End.
