(* Test 3 - Array Literals
D:DECL-TYPE test
  T:TYPE-PROGRAM
  S:STMT-BLOCK
    D:DECL-USES system
      T:TYPE-UNIT
    D:DECL-VARIABLE arr
      T:TYPE-ARRAY  1.. 5 OF TYPE-INTEGER
      E:EXPR-ARRAY-LITERAL
        EXPR-WORD-LITERAL 457 T:TYPE-INTEGER
        EXPR-WORD-LITERAL 8ae T:TYPE-INTEGER
        EXPR-WORD-LITERAL d05 T:TYPE-INTEGER
        EXPR-WORD-LITERAL 115c T:TYPE-INTEGER
        EXPR-WORD-LITERAL 15b3 T:TYPE-INTEGER
*)

Program Test;

Var
  arr : Array[1..5] Of Integer = (1111, 2222, 3333, 4444, 5555);

Begin
End.
