(* Test 0 - Test injecting system unit
decl test 
  symtab
    assign SYMBOL-GLOBAL L:0 O:0 TYPE-PROCEDURE S:0
    beginswith SYMBOL-GLOBAL L:0 O:0 TYPE-FUNCTION S:1
    chr SYMBOL-GLOBAL L:0 O:0 TYPE-FUNCTION S:1
    close SYMBOL-GLOBAL L:0 O:0 TYPE-PROCEDURE S:0
    comparestr SYMBOL-GLOBAL L:0 O:0 TYPE-FUNCTION S:1
    contains SYMBOL-GLOBAL L:0 O:0 TYPE-FUNCTION S:1
    cos SYMBOL-GLOBAL L:0 O:0 TYPE-FUNCTION S:4
    endswith SYMBOL-GLOBAL L:0 O:0 TYPE-FUNCTION S:1
    eof SYMBOL-GLOBAL L:0 O:0 TYPE-FUNCTION S:1
    erase SYMBOL-GLOBAL L:0 O:0 TYPE-PROCEDURE S:0
    forreal SYMBOL-GLOBAL L:1 O:1 TYPE-REAL S:4
    getkey SYMBOL-GLOBAL L:0 O:0 TYPE-FUNCTION S:1
    getkeynowait SYMBOL-GLOBAL L:0 O:0 TYPE-FUNCTION S:1
    ioresult SYMBOL-GLOBAL L:0 O:0 TYPE-FUNCTION S:2
    length SYMBOL-GLOBAL L:0 O:0 TYPE-FUNCTION S:1
    lowercase SYMBOL-GLOBAL L:0 O:0 TYPE-FUNCTION S:2
    myint SYMBOL-GLOBAL L:1 O:0 TYPE-INTEGER S:2
    odd SYMBOL-GLOBAL L:0 O:0 TYPE-FUNCTION S:1
    peek SYMBOL-GLOBAL L:0 O:0 TYPE-FUNCTION S:1
    peekl SYMBOL-GLOBAL L:0 O:0 TYPE-FUNCTION S:4
    peekw SYMBOL-GLOBAL L:0 O:0 TYPE-FUNCTION S:2
    poke SYMBOL-GLOBAL L:0 O:0 TYPE-PROCEDURE S:0
    pokel SYMBOL-GLOBAL L:0 O:0 TYPE-PROCEDURE S:0
    pokew SYMBOL-GLOBAL L:0 O:0 TYPE-PROCEDURE S:0
    rastercb SYMBOL-GLOBAL L:1 O:0 TYPE-ROUTINE-POINTER S:4
    rename SYMBOL-GLOBAL L:0 O:0 TYPE-PROCEDURE S:0
    reset SYMBOL-GLOBAL L:0 O:0 TYPE-PROCEDURE S:0
    rewrite SYMBOL-GLOBAL L:0 O:0 TYPE-PROCEDURE S:0
    setrastercallback SYMBOL-GLOBAL L:0 O:0 TYPE-PROCEDURE S:0
    sin SYMBOL-GLOBAL L:0 O:0 TYPE-FUNCTION S:4
    stringofchar SYMBOL-GLOBAL L:0 O:0 TYPE-FUNCTION S:2
    strpos SYMBOL-GLOBAL L:0 O:0 TYPE-FUNCTION S:1
    tan SYMBOL-GLOBAL L:0 O:0 TYPE-FUNCTION S:4
    trim SYMBOL-GLOBAL L:0 O:0 TYPE-FUNCTION S:2
    upcase SYMBOL-GLOBAL L:0 O:0 TYPE-FUNCTION S:2
  decl myint L:1 O:0 TYPE-INTEGER S:2
  decl forreal L:1 O:1 TYPE-REAL S:4
*)

Program Test;

Var
  myint : Integer;
  forreal : Real;

Begin
End.
