site_name: Pascal65 Documentation
theme: readthedocs
nav:
  - Home: index.md
  - Why Pascal: whypascal.md
  - System Requirements: sysreqs.md
  - Notable Differences: notablediffs.md
  - Limitations: limits.md
  - Pascal Language Syntax:
    - Pascal Syntax: langref/syntax.md
    - Data Types: langref/datatypes.md
    - Arrays: langref/arrays.md
    - Records: langref/records.md
    - Operators: langref/operators.md
    - For Loops: langref/for.md
    - If Then Else: langref/ifelse.md
    - Repeat-Until: langref/repeat.md
    - While: langref/while.md
    - Case: langref/case.md
    - Functions and Procedures: langref/funcproc.md
    - Units: langref/units.md
    - Libraries: langref/libraries.md
  - Function Reference:
    - Abs: funcref/abs.md
    - Chr: funcref/chr.md
    - Length: funcref/length.md
    - Odd: funcref/odd.md
    - Ord: funcref/ord.md
    - Peek: funcref/peek.md
    - Poke: funcref/poke.md
    - Pred: funcref/pred.md
    - Sqr: funcref/sqr.md
    - Succ: funcref/succ.md
    - Trim: funcref/trim.md
