site_name: Pascal65 Documentation
theme: readthedocs
nav:
  - Home: index.md
  - Why Pascal: whypascal.md
  - System Requirements: sysreqs.md
  - Notable Differences: notablediffs.md
  - Limitations: limits.md
  - Usage: usage.md
  - Pascal Language Syntax:
    - Pascal Syntax: langref/syntax.md
    - Comments: langref/comments.md
    - Data Types: langref/datatypes.md
    - Strings: langref/strings.md
    - Arrays: langref/arrays.md
    - Records: langref/records.md
    - Operators: langref/operators.md
    - For Loops: langref/for.md
    - If Then Else: langref/ifelse.md
    - Repeat-Until: langref/repeat.md
    - While: langref/while.md
    - Case: langref/case.md
    - Functions and Procedures: langref/funcproc.md
    - Units: langref/units.md
    - Libraries: langref/libraries.md
  - Function Reference:
    - Abs: funcref/abs.md
    - Chr: funcref/chr.md
    - GetKey : funcref/getkey.md
    - Length: funcref/length.md
    - LowerCase: funcref/lowercase.md
    - Odd: funcref/odd.md
    - Ord: funcref/ord.md
    - Peek: funcref/peek.md
    - Poke: funcref/poke.md
    - Pred: funcref/pred.md
    - Sqr: funcref/sqr.md
    - StringOfChar: funcref/strofchar.md
    - Succ: funcref/succ.md
    - Trim: funcref/trim.md
    - UpCase: funcref/upcase.md
    - Write: funcref/write.md
    - WriteLn: funcref/write.md
    - WriteStr: funcref/write.md
  - Screen Library:
    - ClearScreen: screen/clearscreen.md
    - DrawChar: screen/drawchar.md
    - DrawCharRaw: screen/drawcharraw.md
    - DrawText: screen/drawtext.md
    - DrawTextRaw: screen/drawtextraw.md
    - GetScreenSize: screen/getscreensize.md
    - SetBackgroundColor: screen/setbackgroundcolor.md
    - SetBorderColor: screen/setbordercolor.md
    - SetLowerCase: screen/setlowercase.md
    - SetReverse: screen/setreverse.md
    - SetScreenSize: screen/setscreensize.md
    - SetTextColor: screen/settextcolor.md
    - SetUpperCase: screen/setuppercase.md
