site_name: Pascal65 Documentation
theme: readthedocs
markdown_extensions:
  - admonition
nav:
  - Home: index.md
  - Why Pascal: whypascal.md
  - Notable Differences: notablediffs.md
  - Limitations: limits.md
  - Usage: usage.md
  - Building Pascal65: building.md
  - Future Wishlist: future.md
  - Pascal Language Syntax:
    - Pascal Syntax: langref/syntax.md
    - Comments: langref/comments.md
    - Variables: langref/variables.md
    - Data Types: langref/datatypes.md
    - Strings: langref/strings.md
    - Arrays: langref/arrays.md
    - Records: langref/records.md
    - Operators: langref/operators.md
    - For Loops: langref/for.md
    - If Then Else: langref/ifelse.md
    - Repeat-Until: langref/repeat.md
    - While: langref/while.md
    - Case: langref/case.md
    - Functions and Procedures: langref/funcproc.md
    - Variable Scope: langref/scope.md
    - Units: langref/units.md
    - Libraries: langref/libraries.md
  - Function Reference:
    - Abs: funcref/abs.md
    - BeginsWith: funcref/beginswith.md
    - Chr: funcref/chr.md
    - Contains: funcref/contains.md
    - CompareStr: funcref/comparestr.md
    - Cos: funcref/cos.md
    - Dec: funcref/dec.md
    - EndsWith: funcref/endswith.md
    - GetKey : funcref/getkey.md
    - Inc: funcref/inc.md
    - Length: funcref/length.md
    - LowerCase: funcref/lowercase.md
    - Odd: funcref/odd.md
    - Ord: funcref/ord.md
    - Peek: funcref/peek.md
    - Poke: funcref/poke.md
    - Pred: funcref/pred.md
    - Read: funcref/read.md
    - ReadLn: funcref/read.md
    - ReadStr: funcref/read.md
    - Sin: funcref/sin.md
    - Sqr: funcref/sqr.md
    - StringOfChar: funcref/strofchar.md
    - StrPos: funcref/strpos.md
    - Succ: funcref/succ.md
    - Tan: funcref/tan.md
    - Trim: funcref/trim.md
    - UpCase: funcref/upcase.md
    - Write: funcref/write.md
    - WriteLn: funcref/write.md
    - WriteStr: funcref/write.md
  - Screen Library:
    - ClearScreen: screen/clearscreen.md
    - DrawChar: screen/drawchar.md
    - DrawCharRaw: screen/drawcharraw.md
    - DrawText: screen/drawtext.md
    - DrawTextRaw: screen/drawtextraw.md
    - GetScreenSize: screen/getscreensize.md
    - SetBackgroundColor: screen/setbackgroundcolor.md
    - SetBorderColor: screen/setbordercolor.md
    - SetLowerCase: screen/setlowercase.md
    - SetReverse: screen/setreverse.md
    - SetScreenSize: screen/setscreensize.md
    - SetTextColor: screen/settextcolor.md
    - SetUpperCase: screen/setuppercase.md
  - Developing Libraries:
    - Introduction to Libraries: libraries/libraries.md
    - Interface File: libraries/interface.md
    - Object File: libraries/objfile.md
    - Runtime Stack: libraries/stack.md
    - Runtime Library: libraries/runtime.md
    - Writing Routines: libraries/routines.md
    - Memory Heap: libraries/memheap.md
    - Demo Library: libraries/demolib.md
  - Runtime Library:
    - Introduction: runtime/intro.md
    - Add: runtime/add.md
    - Divide: runtime/divide.md
    - DivInt: runtime/divint.md
    - HeapAlloc: runtime/heapalloc.md
    - HeapFree: runtime/heapfree.md
    - LibLoadParam: runtime/libloadparam.md
    - LibReturnValue: runtime/libreturnvalue.md
    - LibStoreVarParam: runtime/libstorevarparam.md
    - Multiply: runtime/multiply.md
    - PopEax: runtime/popeax.md
    - PushEax: runtime/pusheax.md
    - Subtract: runtime/subtract.md
  - Intermediate Code:
    - Introduction: icode/intro.md
    - Literals: icode/literals.md
    - Data Types: icode/types.md
    - Instructions:
      - ABS: icode/mne/abs.md
      - ADD: icode/mne/add.md
      - AIX: icode/mne/aix.md
      - AND: icode/mne/and.md
      - ARR: icode/mne/arr.md
      - ASF: icode/mne/asf.md
      - BIF: icode/mne/bif.md
      - BIT: icode/mne/bit.md
      - BRA: icode/mne/bra.md
      - BSL: icode/mne/bsl.md
      - BSR: icode/mne/bsr.md
      - BWA: icode/mne/bwa.md
      - BWC: icode/mne/bwc.md
      - BWO: icode/mne/bwo.md
      - CCT: icode/mne/cct.md
      - CNL: icode/mne/cnl.md
      - CPY: icode/mne/cpy.md
      - DEC: icode/mne/dec.md
      - DEL: icode/mne/del.md
      - DIV: icode/mne/div.md
      - DVI: icode/mne/dvi.md
      - EQU: icode/mne/equ.md
      - FSO: icode/mne/fso.md
      - GRT: icode/mne/grt.md
      - GTE: icode/mne/gte.md
      - INC: icode/mne/inc.md
      - INP: icode/mne/inp.md
      - JSR: icode/mne/jsr.md
      - LOC: icode/mne/loc.md
      - LSE: icode/mne/lse.md
      - LST: icode/mne/lst.md
      - MOD: icode/mne/mod.md
      - MUL: icode/mne/mul.md
      - NEG: icode/mne/neg.md
      - NEQ: icode/mne/neq.md
      - NEW: icode/mne/new.md
      - NOT: icode/mne/not.md
      - ONL: icode/mne/onl.md
      - ORA: icode/mne/ora.md
      - OUT: icode/mne/out.md
      - POF: icode/mne/pof.md
      - POP: icode/mne/pop.md
      - PRE: icode/mne/pre.md
      - PSH: icode/mne/psh.md
      - PUF: icode/mne/puf.md
      - ROU: icode/mne/rou.md
      - SCV: icode/mne/scv.md
      - SET: icode/mne/set.md
      - SOF: icode/mne/sof.md
      - SQR: icode/mne/sqr.md
      - SSP: icode/mne/ssp.md
      - SSR: icode/mne/ssr.md
      - SSW: icode/mne/ssw.md
      - SST: icode/mne/sst.md
      - SUB: icode/mne/sub.md
      - SUC: icode/mne/suc.md
      - TRU: icode/mne/tru.md

